/**
 * --------------------------------------------------
 * Component: Landing (Page)
 *
 * Purpose:
 *   The main interactive landing page. Hosts the
 *   full-screen card slider, background effects,
 *   and floating navigation controls.
 *
 * Responsibilities:
 *   - Own and manage the activeIndex slider state
 *   - Persist activeIndex in sessionStorage for
 *     back-navigation memory
 *   - Render crossfading background gradient/image
 *   - Render BackgroundTypography (giant faded word)
 *   - Render the Slider component with all cards
 *   - Render the BottomNavigation control panel
 *   - Play entry animations for top header text
 *
 * State:
 *   activeIndex {number} — Index of the active card (0–4)
 *     Initialised from sessionStorage or defaults to 0.
 *     Persisted to sessionStorage on every change.
 *
 * Dependencies:
 *   - framer-motion (motion, AnimatePresence)
 *   - data/sliderData
 *   - components/Slider
 *   - components/BottomNavigation
 *   - components/BackgroundTypography
 *
 * Reusable: No (page component)
 *
 * EDIT GUIDE: To change card data/backgrounds/typography,
 *   edit src/data/sliderData.js — do NOT edit this file.
 * --------------------------------------------------
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { sliderData } from '../../data/sliderData';
import Slider from '../../components/Slider/Slider';
import BottomNavigation from '../../components/BottomNavigation/BottomNavigation';
import BackgroundTypography from '../../components/BackgroundTypography/BackgroundTypography';
import styles from './Landing.module.css';

const Landing = () => {
  const [activeIndex, setActiveIndex] = useState(() => {
    const saved = sessionStorage.getItem('portfolioActiveIndex');
    return saved !== null ? parseInt(saved, 10) : 0;
  });

  const handleSetActiveIndex = (index) => {
    // If receiving a function (e.g. from prev => ... updater), resolve it
    if (typeof index === 'function') {
      setActiveIndex((prev) => {
        const nextVal = index(prev);
        sessionStorage.setItem('portfolioActiveIndex', nextVal.toString());
        return nextVal;
      });
    } else {
      setActiveIndex(index);
      sessionStorage.setItem('portfolioActiveIndex', index.toString());
    }
  };

  const currentCard = sliderData[activeIndex];

  return (
    <main className={styles.landingContainer}>
      {/* Dynamic Background Layer (Crossfade) */}
      <div className={styles.backgroundTrack}>
        <AnimatePresence mode="popLayout">
          <motion.div
            key={activeIndex}
            className={styles.backgroundImage}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.8 }}
            style={{
              background: currentCard.bgImage 
                ? `url(${currentCard.bgImage}) center/cover no-repeat` 
                : currentCard.bgGradient,
            }}
          />
        </AnimatePresence>
        <div className={styles.bgOverlay} />
      </div>

      {/* Large Background Typography behind the Slider */}
      <BackgroundTypography text={currentCard.bgTypography} />

      {/* Hero Intro Header (Top small text) */}
      <header className={styles.topHeader}>
        <motion.span 
          className={styles.logo}
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          CREATIVE SHOWCASE
        </motion.span>
        <motion.p 
          className={styles.intro}
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.3 }}
        >
          Apple-inspired minimal portfolio landing page. Click or swipe to navigate.
        </motion.p>
      </header>

      {/* Slider Section */}
      <section className={styles.sliderSection}>
        <Slider 
          cards={sliderData} 
          activeIndex={activeIndex} 
          setActiveIndex={handleSetActiveIndex} 
        />
      </section>

      {/* Bottom Floating Nav Panel */}
      <BottomNavigation 
        cards={sliderData} 
        activeIndex={activeIndex} 
        setActiveIndex={handleSetActiveIndex} 
        accentColor={currentCard.accentColor}
      />
    </main>
  );
};

export default Landing;
